### ISSUE TITLE
[BUG] Rendering issues with the pieces.

### ISSUE THREAD

**Issue by litjohn50** [andrew0030/Table-Top-Craft#1]
**Describe the bug**
The Board Pieces are always rendered. No matter if its glass/ solid blocks or anything really, The Pieces on the black side are hollow and vanish if your playing on that side.

**To Reproduce**
1. Start a New Game
2. Walk around and see that it is rendering everywhere.
3. Walk to the black side of the board and look at the pieces

**Expected behavior**
Have Normal Rendering where you don't see it though solid blocks. Where pieces have the same render from all sides of the table.

**Screenshots**
https://gyazo.com/04216da57069307c5ee9ffd0b4280795

**Versions**
Forge: 36.1.4
TableTopCraft: 1.16-1.1.0

**Comment by andrew0030** [comment]
Looks like a mod conflict to me, Optifine is one of tho mods that causes issues similar to this. But regardless I will be dropping an update soon that reworks the render system completely, that should fix all of these issues.
