### ISSUE TITLE
update to latest

### ISSUE THREAD

**Issue by spaghettube** [andrew0030/Table-Top-Craft#15]
Hello, mod dev andrew. I've come to ask you to update the mod to 1.19.2 since i would very much enjoy losing against my friends in chess on 1.19.2. Really though, really cool mod, please update to 1.19.2 :)

**Comment by andrew0030** [comment]
1.19 should work on 1.19.2
I was going to properly test and update it to 1.19.2, but I found some bugs in Swampier Swamps I wanted to take care of.
But any how, try 1.19 which should work, and if it doesn't wait for the new version which I will drop soon.

**Comment by spaghettube** [comment]
sounds good, 'preciatte it
