### ISSUE TITLE
[BUG]Table top does not like Fabric API

### ISSUE THREAD

**Issue by Kingtoast1st** [andrew0030/Table-Top-Craft#17]
So when I launch the game I get this error

"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-renderer-indigo'!"

Exit Code: -1

So I went and digged through the crash report and found that 'fabric-renderer-indigo' is in Fabric API

To Reproduce
Download Recent version of Fabric API and Fabric Launcher for 1.19.2
Download version table_top_craft 1.19.2-2.0.2
Put it in your mod folder
Launch the game

Versions
Fabric 1.19.2

PS
It also doesn't like some other mods and gives me the same error code but the 'fabric-renderer-indigo' is replaced with the mod name
EX:"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'drinkbeer'!"

**Comment by andrew0030** [comment]
A friend of mine just tested TTC fabric 1.19.2 with both the latest Fabric and FAPI version and it seems to work just fine.
Maybe a different Mod thats causing it?

I need a full log to be able to determine anything.
Also do try to run the game only with TTC and fabric to see if its really TTC that causes the crash. If it isnt keep adding mods until you find the culprit.

**Comment by Kingtoast1st** [comment]
Nvm, Found out it was Opti-fabric, thanks for the help
