### ISSUE TITLE
[BUG] New game doesn't work 1.19.2

### ISSUE THREAD

**Issue by Macpr0** [andrew0030/Table-Top-Craft#19]
**Describe the bug**
After I've placed the chess board and wanted to start a new game, nothing happens. No pieces appear on my board and no game starts. Also are all of my pieces locked, and when I place a piece there is black square at the ground.

**To Reproduce**
1. Right Click Chess Board
2. Start New Game
3. I'll get thrown out of the chess board
4. The Chess Board is still empty 

**Expected behavior**
There should be figures I can move and play against each other and configure my figures. 

**Screenshots**
![Chess Board](https://user-images.githubusercontent.com/97113325/230619180-8f5f6a87-37bd-461e-b8ea-19071a54dd93.png)

**Versions**
I use the 1.19.2 Forge Version with 129 other Mods. 
Here the Mods if it helps:
[modlist.txt](https://github.com/andrew0030/Table-Top-Craft/files/11179350/modlist.txt)

**Comment by andrew0030** [comment]
Are those Shaders I see?
Turn them off and it should work. The chess piece renderer doesnt work with Shaders, that is why you cant see them in the world.
I will release a fallback system that uses vanilla rendering in the future when Shaders are active, performs a lot worse but it will make it so Shaders work.

But yeah for now its either Shaders or chess pieces.

**Comment by Macpr0** [comment]
You saw right and it works now. Thank you so much, I'd rather beat my friends at Chess than have Shaders!
