### ISSUE TITLE
Crashed when pressing Video on the ingame pause menu

### ISSUE THREAD

**Issue by gglobensky** [andrew0030/Table-Top-Craft#2]
**To Reproduce**
Steps to reproduce the crash:
1. I can't garantee you could reproduce

**Crash log**
https://pastebin.com/SkSQdznt

**Versions**
FML 36.1.0 
Minecraft 1.16.5
table_top_craft-1.16-1.1.0

**Additional context**
I was flying around a Terraforged world without Optifine. I wanted to increase the chunk distance but the game crashed when clicking on "Video" and the crashlog mentioned your mod.

Thanks for the awesome work!

**Comment by andrew0030** [comment]
Not sure why it crashed but I have been working on a render system code rewrite. I will be posting the update soon and it should get rid of all the issues.

**Comment by gglobensky** [comment]
I understand. It never crashed before and never crashed afterwards too so I guess it was a fluke. I thought I'd share it anyways since it may help.

I expect the rewrite should indeed correct the error that occured.

Thank you for the followup.

**Comment by andrew0030** [comment]
I shall close this bug report now as its old and rendering has been reworked.
