### ISSUE TITLE
QoL: Modrinth

### ISSUE THREAD

**Issue by sargeow** [andrew0030/Table-Top-Craft#23]
Sorry about writing this as a bug on git but its the only place i see for contacting you. anyhow would it be possible for you to upload tabletop craft to Modrinth? it would make sending mod packs to friends much easier via the export feature. Thanks!

**Comment by andrew0030** [comment]
I took some time to create a Modrinth account and to upload TTC to Modrinth, at this point Im just waiting for it to pass review, and once that happens I will drop a link here!

**Comment by andrew0030** [comment]
K its finally approved.
https://modrinth.com/mod/table-top-craft
