### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Doodes** [andrew0030/Table-Top-Craft#3]
**Describe the bug**
I can`t click on the table, while holding any weapon from CGM 1 16 5 in my left hand

**To Reproduce**
1. Download CGM 1 16 5
2. Get any CGM weapon in your left hand
3. Try to shift+right click on any table

**Expected behavior**
Open the table settings menu

**Screenshots**
???

**Debug crash log**
https://gist.githubusercontent.com/natanfudge/bb40359576f3b50030f696199e579894/raw/7c2b6f29aa1d437fec7d48a26caf2b5aa63f1cd1/crash.txt
i used not enough crashes, will it affect?

**Versions**
cgm-1.0.1-1.16.3, table_top_craft-1.16-1.2.0.

**Additional context**
nothing.

**Comment by andrew0030** [comment]
This isn't really a bug, and the mod version this was for is ancient. So I'm closing this issue now.
