### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by Tenuuu** [andrew0030/Table-Top-Craft#8]
**To Reproduce**
Steps to reproduce the crash:
1. Install latest version of Table Top Craft (1.0.1 for Fabric)
2. Launch Minecraft and view crash

**Crash log**
https://gist.github.com/Tenuuu/8e629cadd87857bd251ee6fa5ec27b91

**Screenshots**
N/A

**Versions**
Mod Version: 1.0.1 Fabric

**Additional context**
https://gist.github.com/Tenuuu/6337bc5c46764b2f7836ee1666b9b8ab
Logs here contain all mods used and any additional info needed to figure out the issue.

**Comment by andrew0030** [comment]
I'll look into this. It must have slipped my radar while testing it with other mods.

**Comment by GiantLuigi4** [comment]
Pretty sure this is a me problem, actually

**Comment by andrew0030** [comment]
This should be fixed with the 1.18.2-1.0.2 version.
I'm uploading the file as I'm writing this, so if its not on curse yet, it will likely pop up soon!
